-- -- -- -- -- -- -- --
-- -- -- v 1.1 -- -- --
-- -- -- -- -- -- -- --
-- 
-- create table hibernate_sequence (
-- 	next_val bigint
-- );
-- 
-- insert into hibernate_sequence values ( 1 );

-- CREATE SCHEMA IF NOT EXISTS test_schema

-- CREATE TABLE IF NOT EXISTS public.test_issues (
-- 	issue_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
-- 	title varchar(300) NOT NULL,
-- 	description varchar(5000) NULL,
-- 	parent_id integer NULL,
-- 	manager_id integer NULL,
-- 	initiator_id integer NULL,
-- 	type_id integer NULL,
-- 	status_id integer NULL,
-- 	work_app_id integer NULL,
-- 	date_start timestamp NULL,
-- 	date_end timestamp NULL,
-- 	additional_data jsonb NULL,
-- 	CONSTRAINT issues_pkey PRIMARY KEY (issue_id)
-- );

