-- ALTER TABLE public.tasks ADD price  int4 NULL
-- alter table public.tasks add column status_id int4 null
-- alter table public.tasks add column price int4 null
-- ALTER TABLE public.tasks RENAME COLUMN parent_task_id TO parent_id;
-- INSERT INTO dbo.issues (issue_id, title) values (1, '====-- flyway insert v2 =========');
